import bcrypt from 'bcryptjs';

/*const data = {
  users: [
    {
      name: 'Eni',
      email: 'enize2000@gmail.com',
      password: bcrypt.hashSync('root'),
      isAdmin: true,
    },
    {
      name: 'Fil',
      email: 'fil@gmail.com',
      password: bcrypt.hashSync('root'),
      isAdmin: false,
    },
  ],
};*/

const data = {
  products: [
    {
      name: 'Camicia floreale',
      slug: 'camicia-floreale',
      category: 'Shirt',
      image: '/images/p1.jpg',
      price: 120,
      rating: 4.5,
      description: 'high quality product',
      countInStock: 3,
    },
    {
      name: 'Pantalone slim',
      slug: 'pantalone-slim',
      category: 'Pants',
      image: '/images/p2.jpg',
      price: 80,
      rating: 4,
      description: 'high quality product',
      countInStock: 200,
    },
    {
      name: 'T-shirt essential',
      slug: 't-shirt-essential',
      category: 'T-shirt',
      image: '/images/p3.jpg',
      price: 10,
      rating: 5,
      description: 'high quality product',
      countInStock: 400,
    },
    {
      name: 'Camicia',
      slug: 'camicia-semplice',
      category: 'Shirt',
      image: '/images/p4.jpg',
      price: 75,
      rating: 4,
      description: 'high quality product',
      countInStock: 500,
    },
    {
      name: 'Scarpe Nike',
      slug: 'scarpe-nike',
      category: 'Shoes',
      image: '/images/p5.jpg',
      price: 220,
      rating: 4,
      description: 'high quality product',
      countInStock: 3,
    },
    {
      name: 'Scarpe Maison Margiela',
      slug: 'scarpe-maison-margiela',
      category: 'Shoes',
      image: '/images/p6.jpg',
      price: 400,
      rating: 4,
      description: 'high quality product',
      countInStock: 200,
    },
    {
      name: 'Scarpe Rick Owens',
      slug: 'scarpe-rick-owens',
      category: 'Shoes',
      image: '/images/p7.jpg',
      price: 595,
      rating: 4,
      description: 'high quality product',
      countInStock: 200,
    },
    {
      name: 'Arcteryx',
      slug: 'giacca-arcteryx',
      category: 'Jacket',
      image: '/images/p8.jpg',
      price: 595,
      rating: 4,
      description: 'high quality product',
      countInStock: 200,
    },
    {
      name: 'Helmut lang',
      slug: 'giacca-helmut-lang',
      category: 'Jacket',
      image: '/images/p9.jpg',
      price: 700,
      rating: 5,
      description: 'high quality product',
      countInStock: 400,
    },
    {
      name: 'T-shirt Supreme',
      slug: 't-shirt-supreme',
      category: 'T-shirt',
      image: '/images/p10.jpg',
      price: 239,
      rating: 5,
      description: 'high quality product',
      countInStock: 20,
    },
  ],
};
export default data;
